# Generated by Django 3.0.7 on 2023-10-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_transferout_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferout',
            name='transaction',
        ),
    ]
