# Generated by Django 3.0.7 on 2023-10-25 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_transferout_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferout',
            name='controlnumber',
        ),
        migrations.AddField(
            model_name='transferout',
            name='control_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Control Number'),
        ),
        migrations.AlterField(
            model_name='transferout',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='Control Number'),
        ),
        migrations.AlterField(
            model_name='transferout',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transferout',
            name='motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.TransactionType'),
        ),
    ]
