# Generated by Django 3.0.7 on 2023-10-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_transferin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferin',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transferout',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='RepoIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(blank=True, null=True, verbose_name='Branch')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Motor')),
            ],
        ),
    ]
