# Generated by Django 3.0.7 on 2023-10-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20231027_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoin',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch'),
        ),
    ]
