# Generated by Django 3.0.7 on 2023-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20231027_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferin',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='transferin',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='transferout',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='transferout',
            name='motor',
        ),
        migrations.AddField(
            model_name='transferout',
            name='transferto',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='TransferTo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_release',
            field=models.DateField(blank=True, null=True, verbose_name='Date Release'),
        ),
        migrations.AlterField(
            model_name='transferout',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='RepoIn',
        ),
        migrations.DeleteModel(
            name='TransferIn',
        ),
    ]
