# Generated by Django 3.0.7 on 2023-10-28 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_transferin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferin',
            name='controlnumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Control Number'),
        ),
        migrations.AlterField(
            model_name='transferout',
            name='controlnumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Control Number'),
        ),
        migrations.AlterField(
            model_name='transferout',
            name='transferto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Branch'),
        ),
    ]
