# Generated by Django 4.2.6 on 2023-11-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_status_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='brand',
            field=models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
