# Generated by Django 4.2.6 on 2023-11-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_motor_brand_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
