# Generated by Django 4.2.6 on 2023-11-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_transferout_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlnumber', models.IntegerField(blank=True, null=True, verbose_name='Control Number')),
                ('transferfrom_date', models.DateField(blank=True, null=True, verbose_name='Transfer From Date')),
                ('transferto_date', models.DateField(blank=True, null=True, verbose_name='Transfer To Date')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.inventory')),
                ('transferfrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from_branch', to='inventory.branch')),
                ('transferfromstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from_status', to='inventory.status')),
                ('transferto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to_branch', to='inventory.branch')),
                ('transfertostatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to_status', to='inventory.status')),
            ],
        ),
        migrations.RemoveField(
            model_name='transferout',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='transferout',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transferout',
            name='transferto',
        ),
        migrations.DeleteModel(
            name='TransferIn',
        ),
        migrations.DeleteModel(
            name='TransferOut',
        ),
    ]
