# Generated by Django 4.2.6 on 2023-11-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_transfer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transferfrom_date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transferto_date',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transferin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transfer In Date'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transferout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transfer Out Date'),
        ),
    ]
