# Generated by Django 4.2.6 on 2023-11-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
