# Generated by Django 4.2.6 on 2023-11-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_customer_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
    ]
