# Generated by Django 4.2.6 on 2023-11-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_releaseout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseout',
            name='inventory',
        ),
        migrations.AddField(
            model_name='releaseout',
            name='customer_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer_history'),
        ),
    ]
