# Generated by Django 4.2.6 on 2023-11-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_releaseout_customer_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseout',
            name='status',
            field=models.CharField(default='Release Out', max_length=255),
        ),
    ]
