# Generated by Django 4.2.6 on 2023-11-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_remove_releaseout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseout',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.status'),
        ),
    ]
