# Generated by Django 4.2.6 on 2023-11-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_releaseout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='inventory',
        ),
    ]
