# Generated by Django 4.2.6 on 2023-11-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_remove_customer_comaker_customer_history_comaker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_History',
            new_name='Customer_Released',
        ),
    ]
