# Generated by Django 4.2.6 on 2023-11-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_rename_customer_history_customer_released'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseOut',
        ),
    ]
