# Generated by Django 4.2.6 on 2023-11-15 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_comaker_branch_payment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_released',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.branch'),
        ),
    ]
