# Generated by Django 4.2.6 on 2023-11-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_customer_released_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.DeleteModel(
            name='RepoIn',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
