# Generated by Django 4.2.6 on 2023-11-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_click'),
    ]

    operations = [
        migrations.DeleteModel(
            name='click',
        ),
    ]
